# Generated by Django 4.0.3 on 2022-03-16 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='show',
            new_name='season',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='name',
            new_name='title',
        ),
    ]
