# Generated by Django 4.0.3 on 2022-03-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_movietracks_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
